import numpy as np
import cv2,os,time
import cv2.aruco as aruco

def make_folder(name):
  try:
    os.system("mkdir "+name)
  except: #if already exists?
    pass

def save_tags(aruco_dict,name,num,resolution=512):
  for i in range(num):
    im = aruco.drawMarker(aruco_dict,i,resolution)
    cv2.imwrite(name+str(i)+".jpg",im)


def generate_tags(dict_name,outfilename,quantity=100):
  aruco_dict = aruco.Dictionary_get(dict_name)
  save_tags(aruco_dict,outfilename,quantity)



if(__name__ == "__main__"):
  print("you are running this file as a standalone program.")
  print("tags being outputed will be saved to autogenerated folders in your current directory. Press enter to continue?")
  input() #wait for user to press enter
  make_folder("aruco4x4_250")
  generate_tags(aruco.DICT_4X4_250,"aruco4x4_250/aruco4x4_250_",250)
  print("complete!")
